/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Core palette
        'primary': '#01696f',
        'primary-hover': '#0c4e54',
        'primary-active': '#0f3638',
        'primary-highlight': '#d0e8e6',
        'accent': '#da7101',
        'accent-hover': '#c55700',
        'accent-highlight': '#fde8cc',
        'background': '#f7f6f2',
        'surface': '#ffffff',
        'surface-2': '#f3f0ec',
        'divider': '#e2dfd9',
        'text': '#1a1a1a',
        'text-muted': '#6b6762',
        'text-faint': '#b5b2ad',
        'success': '#437a22',
        'error': '#c0392b',

        // Dark mode
        'dark-background': '#141412',
        'dark-surface': '#1c1b18',
        'dark-surface-2': '#252420',
        'dark-primary': '#4f98a3',
        'dark-accent': '#fdab43',
      },
      fontFamily: {
        'display': ['Plus Jakarta Sans', 'sans-serif'],
        'h1': ['Plus Jakarta Sans', 'sans-serif'],
        'h2': ['Plus Jakarta Sans', 'sans-serif'],
        'h3': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Plus Jakarta Sans', 'sans-serif'],
        'price': ['Plus Jakarta Sans', 'sans-serif'],
        'price-original': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display': ['2rem', { lineHeight: '1.2', fontWeight: '700' }],
        'h1': ['1.5rem', { lineHeight: '1.3', fontWeight: '700' }],
        'h2': ['1.25rem', { lineHeight: '1.35', fontWeight: '600' }],
        'h3': ['1.125rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['0.9375rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label': ['0.875rem', { lineHeight: '1.4', fontWeight: '500' }],
        'label-caps': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'price': ['1.375rem', { lineHeight: '1.2', fontWeight: '700' }],
        'price-original': ['0.9375rem', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'page-margin-mobile': '16px',
        'page-margin-desktop': '32px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'ambient': '0 8px 30px rgba(30, 27, 20, 0.06)',
        'sm': '0 1px 3px rgba(30, 27, 20, 0.07)',
        'card': '0 4px 14px rgba(30, 27, 20, 0.09)',
        'lg': '0 12px 36px rgba(30, 27, 20, 0.13)',
        'nav': '0 -2px 12px rgba(30, 27, 20, 0.06)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
